/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeBlock: typeof import('./../components/CodeBlock/index.vue')['default']
    ConfirmDialog: typeof import('./../components/common/ConfirmDialog.vue')['default']
    EmptyState: typeof import('./../components/common/EmptyState.vue')['default']
    GlobalApiErrorHandler: typeof import('./../components/GlobalApiErrorHandler.vue')['default']
    LogViewer: typeof import('./../components/LogViewer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBadge: typeof import('./../components/common/StatusBadge.vue')['default']
  }
}
